import SearchContainer from '@/components/SearchContainer/SearchContainer'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <header className="homepage-header">
        <div className="homepage-inner">
          <SearchContainer />
        </div>
    </header>
        {children}</body>
    </html>
  )
}
